# Generated by Django 3.0.6 on 2021-04-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210411_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
