# Generated by Django 3.0.6 on 2021-04-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
